kind: pipeline
type: docker
name: publish

trigger:
  branches:
    - drone_CI
  event:
    - push

steps:
  - name: build&push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mitant127/FlaskTest_1
      tags: droneCI
      dockerfile: ./dockerfile