kind: pipeline
type: docker
name: publish

trigger:
  branches:
    - main
  event:
    - push

steps:
  - name: build&push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mitant/flask_test
      tags: droneci
      dockerfile: ./dockerfile
